Capstone-R-99/BubbLit

bubblit/assets/js/chatTestModule.js

기존 채널 떠남 + 채팅 메세지 하단에 표시함.

---

bubblit/lib/bubblit/accounts.ex
bubblit/lib/bubblit/accounts/user.ex
bubblit/lib/bubblit/application.ex
bubblit/lib/bubblit/bubble_rooms.ex
bubblit/lib/bubblit/bubble_rooms/bubble_log.ex
bubblit/lib/bubblit/bubble_rooms/room.ex
bubblit/lib/bubblit/db/db.ex
bubblit/lib/bubblit/room/room_monitor.ex
bubblit/lib/bubblit/room/room_process.ex
bubblit/lib/bubblit/room/room_registry.ex
bubblit/lib/bubblit/room/room_supervisor.ex
bubblit/lib/bubblit/shared/util.ex
bubblit/lib/bubblit_web/channels/room_channel.ex
bubblit/priv/repo/migrations/20200406081801_create_bubble_logs.exs
bubblit/priv/repo/migrations/20200406081811_create_rooms.exs
bubblit/priv/repo/migrations/20200406081833_create_users.exs
bubblit/priv/repo/migrations/20200406084124_change_room_host_name_column_to_host_user_id.exs
bubblit/test/bubblit/accounts_test.exs
bubblit/test/bubblit/bubble_rooms_test.exs

- DynamicSupervisor를 도입했습니다
-이제 방마다 Process가 하나씩 생성됩니다
- 이런구조
- ![image](https://user-images.githubusercontent.com/52481470/78542838-b9418c00-7832-11ea-86ab-4c80d5189e80.png)
- DB는 함수만 열심히 만들어두고 사용안함
자주 쓰일거같은 건 여따 함수로 뺴서 써주세요 (helper 함수같은거)
`mix etco.migrate`를 한 후 실행해주세요
db 마이그레이션 코드가 추가되었습니당

#6 Supervisor,Registry 도입, DB 스키마 생성. 

---

bubblit/assets/css/chatModule.css
bubblit/assets/js/Component/ChatBox.js
bubblit/assets/js/Component/ChatModule.js
bubblit/package-lock.json
bubblit/package.json

#35 약식으로 오토스크롤 구현 및 창조절시 컨텐츠양 조절

---

bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/shareimage.js
bubblit/lib/bubblit_web/channels/room_channel.ex

이미지 링크 넣는 창이 안 보일 가능성이 높음. 개발자 콘솔에서 창 잠깐 지우고 하면 될거같은데
추후에 해결하겠음.

#36 이미지 공유기능 추가

---

bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/shareimage.js

#36 이미지 링크 입력 영역 제대로 보이도록 함

---

bubblit/assets/css/chatModule.css
bubblit/assets/js/Component/ChatBox.js

#35 가로스크롤바 없앰, 폰트-줄간격 수정

---

bubblit/.babelrc
bubblit/assets/js/Component/ShareSpaceComponent/youtube.js
bubblit/lib/bubblit_web/channels/room_channel.ex
bubblit/package-lock.json
bubblit/package.json
bubblit/webpack.config.js

유튜브 관련 기능 추가

---

bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/Room.js

#48 채팅창 위치 조정

---

bubblit/assets/js/Component/ChatBox.js
bubblit/assets/js/Component/ChatModule.js

#48 스크롤바기능 정상화

---

bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/ShareSpaceComponent/shareimage.js
bubblit/assets/js/Component/ShareSpaceComponent/youtube.js
bubblit/package-lock.json
bubblit/package.json

#48 sharespace

---

bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/Lobby.js
bubblit/lib/bubblit/accounts.ex
bubblit/lib/bubblit/bubble_rooms/room.ex
bubblit/lib/bubblit/db/db.ex
bubblit/lib/bubblit/room/room_monitor.ex
bubblit/lib/bubblit/shared/ets.ex
bubblit/lib/bubblit_web/channels/room_channel.ex
bubblit/lib/bubblit_web/controllers/room_controller.ex
bubblit/lib/bubblit_web/views/room_view.ex
bubblit/priv/repo/migrations/20200509203645_add_users_column_room_table.exs

mix ecto.migrate 해주세요
이제 6명이 방에 등록되면 등록된 사람 말고는 못들어갑니다 그방에
코멘트 참고

#54 room user limit

---

bubblit/assets/js/Component/ShareSpace.js

#0 탭액티브 고침

---

bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/ShareSpace.js
bubblit/lib/bubblit/room/room_monitor.ex
bubblit/lib/bubblit_web/channels/room_channel.ex
bubblit/lib/bubblit_web/controllers/page_controller.ex
bubblit/lib/bubblit_web/router.ex

https://github.com/Capstone-R-99/BubbLit/commit/6c6636571da53a1e301af8896194928015ea4763 History 리팩토링 필수. #66
#54 Presense 연동 (연동만 해둠)
#67 땜빵으로 수정해둠. 추후 제대로 고쳐야함
#65 문제를 수정함

#54 #67 #66 #65

---

bubblit/assets/js/Component/ChatBox.js
bubblit/assets/js/Component/ChatModule.js
bubblit/lib/bubblit/room/room_monitor.ex
bubblit/lib/bubblit_web/router.ex

#65 여전히 버그 터지던거 수정
#54 online Offline 표시 이제 해준다
#67 자잘한 수정

Show online

---

bubblit/assets/css/shareSpace.css
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/LogPanel.js
bubblit/assets/js/Component/ShareSpaceComponent/googledocs.js
bubblit/assets/js/Component/ShareSpaceComponent/shareimage.js
bubblit/assets/js/Component/ShareSpaceComponent/youtube.js

- 탭 조그만해지는 버그 수정함.
수정하는김에 sharespace-tab이라는 class가 div 크기를 맞추기 위해 너무 남용되고 있었음. 외부 div와 크기를 맞추는 용도로 outerfit이라는 class를 따로 만들었으니 단순히 크기 맞추는 정도는 이걸로 할 예정.
- 이미지탭에서 image 렌더 관련 코드 수정함. 저 부분은 순전히 이미지 렌더링만 하는 부분이라 없어도 코드에 지장 없음. 아마 이 관련 부분 위에서도 지울수 있을거 같은데 일단 잘 몰라서 놔둠
- 이미지 가운데정렬 하도록 작업중. 현재는 좌우로만 가운데 정렬이 되...나?

#68 탭 관련 작업함

---

bubblit/.babelrc
bubblit/assets/css/shareSpace.css
bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/Home.js
bubblit/assets/js/Component/Lobby.js
bubblit/assets/js/Component/ShareSpaceComponent/shareimage.js
bubblit/assets/js/Container/ChatModule.js
bubblit/assets/js/Container/Lobby.js
bubblit/assets/js/app.js
bubblit/assets/js/store.js
bubblit/package-lock.json
bubblit/package.json

- 뒤로가기 정상적으로 작동하는데... 모든 상황에서 100% 정상적으로 동작하는지는 확인 불가. 일단 페이지 뒤로가기/앞으로가기가 그냥 url로 이동하는 거랑 동일한 게 아니라서 그런듯.
- TODO 좀 써놨는데 채팅방 입장 로직을 하나로 통일시키는게 제일 급함. 이게 모든 버그의 근원인듯...
가급적 Room.js에서 처리하도록 하는게 좋을듯.
- 이미지 가운데정렬함
- @pula39 gif가 움직이지 않는데, 아마 확장자가 지정되지 않아서 그런 것 같음. blob에서 이미지 확장자까지 알아내는 건 좀 힘들...겠지?

#68 뒤로가기 문제 수정 및 이미지 배치 수정

---

bubblit/assets/css/shareSpace.css
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/googledocs.js
bubblit/assets/js/Component/ShareSpaceComponent/youtube.js
bubblit/assets/js/Container/Room.js
bubblit/lib/bubblit_web/controllers/page_controller.ex
bubblit/lib/bubblit_web/router.ex

#68 #75 데모대비용 수정

---

bubblit/assets/css/login.css
bubblit/lib/bubblit_web/controllers/session_controller.ex
bubblit/lib/bubblit_web/templates/session/new.html.eex
bubblit/lib/bubblit_web/templates/user/form.html.eex
bubblit/lib/bubblit_web/templates/user/new.html.eex

아직 하는중이라 가로는 잘 되는데 세로는 안 되는 버그 있음.

#75 로그인, 회원가입 페이지  디자인

---

bubblit/assets/css/login.css
bubblit/lib/bubblit_web/templates/session/new.html.eex

#75 탭 버튼 버그 수정

---

bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/MediaPanel.js
bubblit/lib/bubblit_web/channels/room_channel.ex

#84 Youtube -> Media로 네이밍 전체적으로 리팩토링함.

---

.github/workflows/elixir.yml
bubblit/config/test.exs

#84 TEST 빌드 환경 명시함

---

bubblit/assets/js/Component/Lobby.js

체크박스로 추가함. 따로 탭으로 둘 필요는 없을거같아서

#95 내가속한 방만 표시하기 옵션 추가 및 리팩토링

---

bubblit/assets/js/Component/Lobby.js

#95 워링소리 상영종료

---

bubblit/assets/js/Component/Room.js
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/MediaPanel.js
bubblit/assets/js/Container/Room.js
bubblit/assets/js/store.js
bubblit/lib/bubblit/room/room_monitor.ex

#104 호스트 id 받아오기 관련 작업함

---

bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/MediaPanel.js

#104 진짜 잘되게 했음

---

bubblit/assets/js/Component/ShareSpaceComponent/CustomPanel.js

#104 커스텀 탭 비활성화

---

bubblit/assets/css/shareSpace.css
bubblit/assets/js/Component/CreateRoom.js
bubblit/assets/js/Component/JoinRoom.js
bubblit/assets/js/Component/Lobby.js
bubblit/assets/js/Component/Room.js
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Container/Lobby.js
bubblit/assets/js/store.js
bubblit/lib/bubblit/bubble_rooms/room.ex
bubblit/lib/bubblit/db/db.ex
bubblit/lib/bubblit_web/channels/room_channel.ex
bubblit/lib/bubblit_web/controllers/room_controller.ex
bubblit/lib/bubblit_web/controllers/room_image_controller.ex
bubblit/priv/repo/migrations/20200603165424_add_room_password_room_table.exs

커밋을 이번엔 의식해서 쪼갰으므로 알기 편할거라 생각.
자잘한 버그, 걍 내가 불편하다 싶은것도 바꿈. 다시 불편하다싶으면 통지식으로 바꿔도됨 (지금 내가 한거처럼)
이게 변경사항이고
비밀방 방 코드 관련해서 생긴 결정사항을 공유하겠음.
- 짜피 방 코드 없으면 못들어감.
- https://github.com/Capstone-R-99/BubbLit/commit/a64ca87b3bffec1f7d76743b2d34be6625b2b240
- 방을 만들때 `자동적으로` 생성됨. 다른 방이랑 `겹칠수도` 있음.
- 방 코드를 조합할 때 씀
- JoinRoom에서 버튼 눌러서 생기는 함수 흐름 쭉 따라가면 알듯
- `{방번호}`:`{방비밀번호}`의 조합.
- 방에 입장해있는 사람만이 알 수 있음. (입장 전에는 알 방법 없음)
- 다른 방이랑 `중복되지 않음`
- 중복되지 않기 때문에 방의 식별자로 쓸 수 있음.
- 비밀방을 입장할 때 쓰인다. (물론 열린 방에 입장할 때도 쓸 수 있다.)
- 방 코드로 입장
- 비밀방이던 열린방이던 입장 가능. 
- 로비에서 방 클릭해서 입장
- 내가 이미 속해있는 방이라면 입장 가능
- 비밀방은 내가 입장해있는 상태가 아니라면 표시되지 않으므로 입장 불가능
- 6명인 비밀방에 입장하는거, 아마 프론트는 그냥 시킬텐데, 백에서는 막아주고있기떄문에 소켓 접근할때 팅길거임. 잘 처리되려나.

#112 private room. Room 제어권 유저가 잘보게 함. 몇가지 버그 수정

---

bubblit/assets/js/Component/Room.js
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/ActionLogPanel.js
bubblit/assets/js/Container/Room.js
bubblit/assets/js/store.js
bubblit/lib/bubblit/bubble_rooms/bubble_log.ex
bubblit/lib/bubblit/db/db.ex
bubblit/lib/bubblit/room/room_monitor.ex
bubblit/lib/bubblit/room/room_supervisor.ex
bubblit/lib/bubblit_web/channels/room_channel.ex
bubblit/priv/repo/migrations/20200603194509_cascade_delete_when_room_delete_room_action.exs

아-------------주 자세하게 테스트는 안해봣음. 간단하게 했을 때 잘돌아가씀.
방장만이 방폭가능. 방폭되면 다른사람은 쫒겨나고 사라짐.

#112 delete room

---

bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/Room.js
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/ActionLogPanel.js
bubblit/assets/js/Component/ShareSpaceComponent/MediaPanel.js
bubblit/assets/js/Container/Room.js
bubblit/assets/js/store.js
bubblit/lib/bubblit_web/channels/room_channel.ex

#109 미디어 호스트(업로더) 기능 구현

---

bubblit/assets/js/Component/ChatBox.js
bubblit/assets/js/Component/ChatModule.js
bubblit/assets/js/Component/CreateRoom.js
bubblit/assets/js/Component/Lobby.js
bubblit/assets/js/Component/Room.js
bubblit/assets/js/Component/ShareSpace.js
bubblit/assets/js/Component/ShareSpaceComponent/ActionLogPanel.js
bubblit/assets/js/Component/ShareSpaceComponent/CustomPanel.js
bubblit/assets/js/Component/ShareSpaceComponent/MediaPanel.js
bubblit/assets/js/app.js
bubblit/package-lock.json
bubblit/package.json

최종데모용 UX 및 텍스트 개선

---

bubblit/assets/js/Component/ChatBox.js

#121 방장 표시

---

bubblit/assets/js/Component/ChatBox.js

#121 충돌난거 마저 수정
